import {FIELDS,GROUPS,REVIEW_ITEMS,MONTHS,DAYS} from './schema.mjs';
import {calculate} from './model.mjs';import {newStudy,readMajor,writeMajor} from './simple.mjs';
import {loadBook,saveBook,serializeBook,parseBackup} from './storage.mjs?v=2';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const loaded=loadBook();let book=loaded.book,paused=!!loaded.error,step=0,timer;
const current=()=>book.properties.find(p=>p.id===book.active)||book.properties[0];
const cash=(v,round=100)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Math.round(v/round)*round);
const screens=[
 {title:'Start with the purchase.',fields:[['price','Purchase price','USD','',true],['down','Down payment','%','',true],['rate','Mortgage rate','%','30-year fixed by default',true],['closing','Closing costs','USD','Lender, title, taxes & inspections',false]]},
 {title:'Get it guest-ready.',fields:[['setup','Repairs & furnishings','USD','Everything needed before the first guest',false],['reserveCash','Cash kept in reserve','USD','Money set aside for slow months',false]]},
 {title:'A typical month.',fields:[['adr','Nightly rate','USD','Before cleaning fees and taxes',true],['occupancy','Nights booked','%','50% is about 15 nights a month',true],['bills','Monthly bills','USD','Property tax, insurance, utilities & HOA',true],['management','Management fee','%','0% if you manage it yourself',false],['cleaningCost','Cleaner charge / stay','USD','',true]]}
];
function save(){if(paused)return;const error=saveBook(book);$('save').textContent=error?'Not saved':'Saved';$('warning').hidden=!error;if(error)$('warning').textContent=error;}
function render(){
 const p=current();$('name').textContent=p.name;$('example').hidden=!p.example;
 document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.step)===step?'step':'false'));
 $('back').hidden=step===0;$('next').hidden=step===3;$('next').textContent=step===2?'See estimate':'Continue';
 if(step===3){results();return;}
 $('screen').innerHTML=`<h1>${screens[step].title}</h1><div class="fields">${screens[step].fields.map(([key,label,unit,hint,required])=>{const v=readMajor(p,key),f=FIELDS.find(f=>f.key===key);return `<div><label for="major-${key}">${label}</label><div class="input"><input id="major-${key}" data-major="${key}" type="number" inputmode="decimal" min="${key==='price'?1:0}" max="${f?.max??100000000}" step="any" ${required&&!(key==='rate'&&p.values.down===100)?'required':''} value="${v==null?'':Math.round(v*100)/100}" placeholder="Your estimate"><span class="unit">${unit}</span></div>${hint?`<small class="hint">${hint}</small>`:''}</div>`;}).join('')}</div>`;
}
function go(n){clearTimeout(timer);save();step=Math.max(0,Math.min(3,n));render();$('screen').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function results(){
 const p=current(),r=calculate(p),a=r.annual;
 if(!r.valid){$('screen').innerHTML=`<h1>Finish the basics.</h1><div class="empty">${esc([...r.errors,...r.missing.map(x=>'Add '+x)].slice(0,4).join(' · '))}</div>`;return;}
 const down=calculate(p,{adrChange:-10,costChange:10}),up=calculate(p,{adrChange:10,costChange:-10});
 $('screen').innerHTML=`<h1>Your rough estimate.</h1><div class="result-main"><small>Cash needed to buy & open</small><div class="amount">≈ ${cash(r.startup.total,1000)}</div><small>Includes setup, contingency and reserves</small></div><div class="result-cash"><span>${a.cashFlow<0?'You would need to cover':'Estimated cash left over'}</span><div class="amount ${a.cashFlow<0?'loss':''}">≈ ${cash(Math.abs(a.cashFlow)/12)}<small> / month</small></div><p>After operating costs, mortgage and replacement reserves. Before tax.</p></div><div class="rows">${[['Income',a.revenue/12],['Running costs',-a.expenses/12],['Mortgage',-a.debtService/12],['Replacement reserve',-a.replacementReserve/12]].map(([label,value])=>`<div class="row"><span>${label} / month</span><b>${cash(value)}</b></div>`).join('')}</div><div class="range"><small>If rates and running costs move by 10%</small><b>${cash(down.annual.cashFlow/12)} to ${cash(up.annual.cashFlow/12)} / month</b><small>What-if range, not a forecast.</small></div>${r.firstYear.additionalCashNeeded>0?`<p class="status loss">First-year shortfall: about ${cash(r.firstYear.additionalCashNeeded,1000)} beyond your planned reserve.</p>`:''}<details><summary>Where the upfront money goes</summary>${r.startup.items.filter(x=>x.amount).map(x=>`<div class="row"><span>${esc(x.label)}</span><b>${cash(x.amount,1000)}</b></div>`).join('')}<p>Already paid: ${cash(p.values.earnest||0,1000)}. Still needed: ${cash(r.startup.remaining,1000)}.</p></details><details><summary>Before you commit · ${r.research.confirmed}/6 checked</summary><div class="research">${REVIEW_ITEMS.map(item=>`<label for="check-${item.key}">${item.label}</label><select id="check-${item.key}" data-review="${item.key}">${[['unknown','Not checked'],['confirmed','Confirmed / not applicable'],['blocked','Problem found']].map(([v,label])=>`<option value="${v}" ${p.research[item.key]===v?'selected':''}>${label}</option>`).join('')}</select>`).join('')}</div></details><p class="status" id="gate-status">${Object.values(p.research).includes('blocked')?'A research concern is flagged. Resolve it before buying.':r.research.confirmed<6?'Check rental permission, insurance and your estimates before buying.':'Based on your inputs, not a purchase recommendation.'}</p><details><summary>What’s assumed?</summary><p>${p.values.contingency}% setup contingency. ${p.values.platform}% booking fees. ${p.values.repairPercent}% routine repairs + ${p.values.replacementPercent}% replacement allowance on lodging income. ${p.values.term}-year fixed mortgage.</p><p>Setup estimates exclude cash reserves. Annual bills are spread across months. First-year timing starts in January. No appreciation or income-tax benefits included.</p></details>`;
}
function advanced(){const p=current();$('advanced').innerHTML=`<p class="advanced-note">Optional. Existing detailed inputs and research notes are retained.</p>${GROUPS.map(g=>`<details><summary>${g.title}</summary><div class="fields">${FIELDS.filter(f=>f.group===g.id).map(f=>`<div><label for="detail-${f.key}">${f.label}${f.unit==='percent'?' (%)':''}</label><input id="detail-${f.key}" data-field="${f.key}" type="number" inputmode="decimal" min="${f.min}" max="${f.max}" step="${f.step}" value="${p.values[f.key]??''}"><details><summary>About this input</summary><p>${esc(f.help)}</p>${p.notes[f.key]?.note?`<p>${esc(p.notes[f.key].note)}</p>`:''}</details></div>`).join('')}</div></details>`).join('')}<details><summary>Seasonal overrides</summary>${MONTHS.map((m,i)=>`<h3>${m}</h3><div class="monthly">${[['adr','Rate',100000000],['occupancy','Occupancy %',100],['blocked','Blocked nights',DAYS[i]]].map(([k,label,max])=>`<div><label for="season-${i}-${k}">${label}</label><input id="season-${i}-${k}" data-month="${i}" data-key="${k}" type="number" min="0" max="${max}" step="${k==='blocked'?1:'any'}" inputmode="decimal" value="${p.months[i][k]??''}" placeholder="Use baseline"></div>`).join('')}</div>`).join('')}</details>`;$('settings').showModal();}
function places(){const p=current();$('select').innerHTML=book.properties.map(x=>`<option value="${esc(x.id)}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('');$('rename').value=p.name;$('places').showModal();}
function add(){if(book.properties.length>=50)return;const p=newStudy();book.properties.push(p);book.active=p.id;step=0;render();save();places();$('rename').focus();$('rename').select();}
$('next').onclick=()=>{const invalid=[...$('screen').querySelectorAll('input')].find(i=>!i.checkValidity()||(i.dataset.major==='price'&&Number(i.value)<=0));if(invalid){invalid.focus();invalid.reportValidity();return;}go(step+1);};$('back').onclick=()=>go(step-1);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.step!==undefined)go(Number(b.dataset.step));if(b?.dataset.close){$(b.dataset.close).close();render();save();}});
document.addEventListener('input',e=>{const el=e.target,p=current();if(el.dataset.major){writeMajor(p,el.dataset.major,el.value===''?null:Number(el.value));if(el.dataset.major==='down'&&$('major-rate'))$('major-rate').required=Number(el.value)!==100;}else if(el.dataset.field)p.values[el.dataset.field]=el.value===''?null:Number(el.value);else if(el.dataset.month!==undefined)p.months[Number(el.dataset.month)][el.dataset.key]=el.value===''?(el.dataset.key==='blocked'?0:null):Number(el.value);else return;clearTimeout(timer);$('save').textContent='Saving…';timer=setTimeout(save,200);});
document.addEventListener('change',e=>{if(e.target.dataset.review){current().research[e.target.dataset.review]=e.target.value;const confirmed=Object.values(current().research).filter(x=>x==='confirmed').length;e.target.closest('details').querySelector('summary').textContent=`Before you commit · ${confirmed}/6 checked`;$('gate-status').textContent=Object.values(current().research).includes('blocked')?'A research concern is flagged. Resolve it before buying.':confirmed<6?'Check rental permission, insurance and your estimates before buying.':'Based on your inputs, not a purchase recommendation.';save();}});
$('fine').onclick=advanced;$('saved').onclick=places;$('new').onclick=add;$('clear-example').onclick=add;$('home').onclick=e=>{e.preventDefault();go(0);};
$('rename').oninput=e=>{current().name=e.target.value;$('name').textContent=e.target.value;save();};$('select').onchange=e=>{save();book.active=e.target.value;step=0;render();$('rename').value=current().name;save();};
$('delete').onclick=()=>{if(!confirm('Delete this property? Export a backup first if you need it.'))return;book.properties=book.properties.filter(p=>p.id!==book.active);if(!book.properties.length)book.properties.push(newStudy());book.active=book.properties[0].id;step=0;render();save();places();};
$('export').onclick=()=>{save();const url=URL.createObjectURL(new Blob([serializeBook(book)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='tideland-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>5000000)throw Error('File is too large.');const incoming=parseBackup(await f.text());if(!confirm('Replace the current fieldbook with this backup?'))return;book=incoming;paused=false;step=0;render();save();places();$('file-status').textContent='Backup restored.';}catch(err){$('file-status').textContent='Import not applied: '+err.message;}};
window.addEventListener('storage',e=>{if(e.key==='tideland.fieldbook.v1'){paused=true;$('warning').hidden=false;$('warning').textContent='Changed in another tab. Saving paused. Export your work or reload.';}});
window.addEventListener('pagehide',()=>{if(!paused)saveBook(book);});
if(!current().example&&calculate(current()).valid)step=3;
render();if(loaded.error){$('warning').hidden=false;$('warning').textContent=loaded.error;}else save();

$('settings').addEventListener('close',()=>{render();save();});
