import {FIELDS,GROUPS,REVIEW_ITEMS,MONTHS,DAYS} from './schema.mjs';
import {calculate} from './model.mjs';import {newStudy,readMajor,writeMajor} from './simple.mjs';
import {loadBook,saveBook,serializeBook,parseBackup} from './storage.mjs?v=4';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const loaded=loadBook();let book=loaded.book,paused=!!loaded.error,step=0,timer;
const current=()=>book.properties.find(p=>p.id===book.active)||book.properties[0];
const cash=(v,round=100)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Math.round(v/round)*round);
const screens=[
 {title:'Start with the purchase.',fields:[['price','Purchase price','USD','',true],['down','Down payment','%','',true],['rate','Mortgage rate','%','30-year fixed by default',true],['closing','Closing costs','USD','Lender, title, taxes & inspections',false]]},
 {title:'Get it guest-ready.',fields:[['setup','Repairs & furnishings','USD','Everything needed before the first guest',false],['reserveCash','Cash kept in reserve','USD','Money set aside for slow months',false]]},
 {title:'A typical month.',fields:[['adr','Nightly rate','USD','Before cleaning fees and taxes',true],['occupancy','Nights booked','%','50% is about 15 nights a month',true],['bills','Monthly bills','USD','Property tax, insurance, utilities & HOA',true],['management','Management fee','%','0% if you manage it yourself',false],['cleaningCost','Cleaner charge / stay','USD','',true]]}
];
function save(){if(paused)return;const error=saveBook(book);$('save').textContent=error?'Not saved':'Saved';$('warning').hidden=!error;if(error)$('warning').textContent=error;}
function render(){
 const p=current();$('name').textContent=p.name==='Untitled property'?'Rental estimate':p.name;$('example').hidden=!p.example;
 $('back').hidden=true;$('next').hidden=true;
 const short={price:'Price',down:'Down payment',rate:'Interest rate',closing:'Closing costs',setup:'Repairs & furniture',reserveCash:'Cash reserve',adr:'Nightly rate',occupancy:'Occupancy',bills:'Monthly bills',management:'Management',cleaningCost:'Cleaning / stay'};
 $('screen').innerHTML='<div id="totals" aria-live="polite"></div>'+screens.map((section,i)=>`<fieldset class="sheet-group"><legend>${['Purchase','Setup','Operation'][i]}</legend><div class="sheet-grid">${section.fields.map(([key,label,unit,hint,required])=>{const v=readMajor(p,key),f=FIELDS.find(f=>f.key===key);return `<div><label for="major-${key}">${short[key]}</label><div class="input"><input id="major-${key}" data-major="${key}" type="number" inputmode="decimal" min="${key==='price'?1:0}" max="${f?.max??100000000}" step="any" ${required&&!(key==='rate'&&p.values.down===100)?'required':''} value="${v==null?'':Math.round(v*100)/100}" placeholder="—"><span class="unit">${unit==='USD'?'$':unit}</span></div></div>`;}).join('')}</div></fieldset>`).join('');
 results();
}
function go(n){clearTimeout(timer);save();step=Math.max(0,Math.min(3,n));render();$('screen').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function results(){
 const el=$('totals');if(!el)return;const p=current(),r=calculate(p),v=r.valid,flow=r.annual.cashFlow/12;
 el.innerHTML=`<div class="total-pair"><div><small>Cash to open</small><strong>${v?'≈ '+cash(r.startup.total,1000):'—'}</strong></div><div><small>Cash flow / month</small><strong class="${v&&flow<0?'loss':''}">${v?'≈ '+cash(flow):'—'}</strong></div></div><div class="estimate-note">${!v?(r.errors.length?'Check highlighted values':'Complete the blank fields'):'Rough estimate · after costs & debt · before tax'}</div>`;
 for(const input of document.querySelectorAll('[data-major]'))input.setAttribute('aria-invalid',String(input.value!==''&&!input.checkValidity()));
}
function advanced(){const p=current();$('advanced').innerHTML=`<details><summary>Rental permission & research</summary>${REVIEW_ITEMS.map(item=>`<label for="check-${item.key}">${item.label}</label><select id="check-${item.key}" data-review="${item.key}">${[['unknown','Not checked'],['confirmed','Confirmed'],['blocked','Problem found']].map(([v,label])=>`<option value="${v}" ${p.research[item.key]===v?'selected':''}>${label}</option>`).join('')}</select>`).join('')}</details>${GROUPS.map(g=>`<details><summary>${g.title}</summary><div class="fields">${FIELDS.filter(f=>f.group===g.id).map(f=>`<div><label for="detail-${f.key}">${f.label}${f.unit==='percent'?' (%)':''}</label><input id="detail-${f.key}" data-field="${f.key}" type="number" inputmode="decimal" min="${f.min}" max="${f.max}" step="${f.step}" value="${p.values[f.key]??''}"><details><summary>About this input</summary><p>${esc(f.help)}</p>${p.notes[f.key]?.note?`<p>${esc(p.notes[f.key].note)}</p>`:''}</details></div>`).join('')}</div></details>`).join('')}<details><summary>Seasonal overrides</summary>${MONTHS.map((m,i)=>`<h3>${m}</h3><div class="monthly">${[['adr','Rate',100000000],['occupancy','Occupancy %',100],['blocked','Blocked nights',DAYS[i]]].map(([k,label,max])=>`<div><label for="season-${i}-${k}">${label}</label><input id="season-${i}-${k}" data-month="${i}" data-key="${k}" type="number" min="0" max="${max}" step="${k==='blocked'?1:'any'}" inputmode="decimal" value="${p.months[i][k]??''}" placeholder="Use baseline"></div>`).join('')}</div>`).join('')}</details>`;$('settings').showModal();}
function places(){const p=current();$('select').innerHTML=book.properties.map(x=>`<option value="${esc(x.id)}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('');$('rename').value=p.name;$('places').showModal();}
function add(){if(book.properties.length>=50)return;const p=newStudy();book.properties.push(p);book.active=p.id;step=0;render();save();places();$('rename').focus();$('rename').select();}
$('next').onclick=()=>{const invalid=[...$('screen').querySelectorAll('input')].find(i=>!i.checkValidity()||(i.dataset.major==='price'&&Number(i.value)<=0));if(invalid){invalid.focus();invalid.reportValidity();return;}go(step+1);};$('back').onclick=()=>go(step-1);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.step!==undefined)go(Number(b.dataset.step));if(b?.dataset.close){$(b.dataset.close).close();render();save();}});
document.addEventListener('input',e=>{const el=e.target,p=current();if(el.dataset.major){writeMajor(p,el.dataset.major,el.value===''?null:Number(el.value));if(el.dataset.major==='down'&&$('major-rate'))$('major-rate').required=Number(el.value)!==100;}else if(el.dataset.field)p.values[el.dataset.field]=el.value===''?null:Number(el.value);else if(el.dataset.month!==undefined)p.months[Number(el.dataset.month)][el.dataset.key]=el.value===''?(el.dataset.key==='blocked'?0:null):Number(el.value);else return;clearTimeout(timer);$('save').textContent='Saving…';timer=setTimeout(save,200);results();});
document.addEventListener('change',e=>{if(e.target.dataset.review){current().research[e.target.dataset.review]=e.target.value;save();}});
$('fine').onclick=advanced;$('saved').onclick=places;$('new').onclick=add;$('clear-example').onclick=add;$('home').onclick=e=>{e.preventDefault();go(0);};
$('rename').oninput=e=>{current().name=e.target.value;$('name').textContent=e.target.value;save();};$('select').onchange=e=>{save();book.active=e.target.value;step=0;render();$('rename').value=current().name;save();};
$('delete').onclick=()=>{if(!confirm('Delete this property? Export a backup first if you need it.'))return;book.properties=book.properties.filter(p=>p.id!==book.active);if(!book.properties.length)book.properties.push(newStudy());book.active=book.properties[0].id;step=0;render();save();places();};
$('export').onclick=()=>{save();const url=URL.createObjectURL(new Blob([serializeBook(book)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='rental-property-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>5000000)throw Error('File is too large.');const incoming=parseBackup(await f.text());if(!confirm('Replace the current fieldbook with this backup?'))return;book=incoming;paused=false;step=0;render();save();places();$('file-status').textContent='Backup restored.';}catch(err){$('file-status').textContent='Import not applied: '+err.message;}};
window.addEventListener('storage',e=>{if(e.key==='tideland.fieldbook.v1'){paused=true;$('warning').hidden=false;$('warning').textContent='Changed in another tab. Saving paused. Export your work or reload.';}});
window.addEventListener('pagehide',()=>{if(!paused)saveBook(book);});
if(!current().example&&calculate(current()).valid)step=3;
render();if(loaded.error){$('warning').hidden=false;$('warning').textContent=loaded.error;}else save();

$('settings').addEventListener('close',()=>{render();save();});
